---
title: "Maestría en Estadística Aplicada<br>Manejo y Visualización de Datos"
subtitle: "Trabajo final"
author: Lic. Qca. Laura Carrau
format: 
  html:
    embed-resources: true
execute:
    echo: true
    warning: false
    message: false
editor: source
toc: true
lang: es
lightbox: true
---

## Objetivo
<div style="text-align: justify;">
El objetivo de este trabajo es generar un producto en el cual se implemente el uso de las herramientas presentadas en la asignatura para el **Manejo y Visualización de Datos**, trabajando con un enfoque ordenado y reproducible.
</div>

## Introducción
<div style="text-align: justify;">
**Internet Archive** es una organización sin fines de lucro fundada en 1996 con la misión de preservar y garantizar el acceso universal al conocimiento. Funciona como una enorme biblioteca digital que almacena páginas web, libros, música, películas, software y otros materiales culturales en formato digital. Su herramienta más conocida es la *Wayback Machine*, que permite consultar versiones archivadas de sitios web a lo largo del tiempo.

**Open Library** es un proyecto de Internet Archive que busca crear una página web para cada libro publicado. Además de ofrecer fichas bibliográficas completas, permite acceder a millones de textos: algunos disponibles para descarga libre por ser de dominio público y otros en préstamo digital, emulando el funcionamiento de una biblioteca tradicional. También es colaborativa, ya que los usuarios pueden contribuir agregando o editando información sobre los libros.
</div>

## Materiales y métodos

<div style="text-align: justify;">
El conjunto de datos seleccionado contiene información del catálogo de libros de Open Library ([Open Library](https://openlibrary.org/ "Un recurso de Internet Archive")) con libros publicados hasta el año 2024. La base de datos se obtuvo del sitio Kaggle ([Kaggle - Open Library Books](https://www.kaggle.com/datasets/jorgeborja/open-library-books-api-12k/data))
</div>

Se realizó una selección de los registros en base a los siguientes criterios:

-   Registros con datos válidos para las variables: Author, description y genres (que no se trate de libros para colorear).

-   average_rating distintos de 0.00

-   num_pages distintos de 0

-   rating_count mayor a 10.

### Descripción del conjunto de datos

<div style="text-align: justify;">
El conjunto de datos crudo consta de 12.185 registros para 14 variables. Luego del proceso de depuración, permanecieron 465 registros.
</div>

| Variable | Tipo de registro | Descripción |
|---------------|---------------|------------------------------------------|
| book_id | caracter | Identificador de OpenLibrary |
| title | caracter | Título del libro |
| author | caracter | Autor del libro |
| description | caracter | Descripción del libro |
| genres | caracter | Géneros y palabras clave |
| first_publish_year | numeric | Año de primera publicación |
| editions | numeric | Cantidad de ediciones |
| num_pages | numeric | Cantidad de páginas |
| cover_m | caracter | Link a la imagen de la tapa - tamaño medio |
| cover_l | caracter | Link a la imagen de la tapa - tamaño grande |
| average_rating | numeric | Puntuación promedio |
| rating_count | numeric | Cantidad de votos |
| id_goodreads | caracter | Identificador de Goodreads |
| id_amazon | caracter | Identificador de Amazon |

: Tabla resumen de las variables y sus características

## Resultados
<div style="text-align: justify;">
Se creó una Shiny App que consta de un panel principal, un panel lateral y dos pestañas. En el panel lateral se puede seleccionar un rango de "Año de primera publicación" y uno o más autores. En la primera pestaña se puede interactuar con un gráfico que muestra la cantidad de votos y la valoración obtenida para los libros selecconados. En la segunda pestaña se presentan cuatro gráficos que muestran los "Top 10" de autores y libros mejor puntuados y con mayor cantidad de ediciones.
</div>

## Conclusiones
<div style="text-align: justify;">
Si bien quedan muchos detalles por afinar, se logró obtener una aplicación interactiva utilizando la información contenida en una base de datos de acceso libre.
</div>

